// Generates src/icons.js (tree-shaken lucide imports) from icon names used in data + UI.
import fs from 'node:fs'
const a = JSON.parse(fs.readFileSync('src/data/answers.json', 'utf8'))
const d = JSON.parse(fs.readFileSync('src/data/dashboard.json', 'utf8'))
const t = JSON.parse(fs.readFileSync('src/data/tables.json', 'utf8'))
const ui = ['Bot','Sparkles','Send','Trash2','RefreshCw','Moon','Sun','LayoutDashboard','Database','MessageSquare','Search','ChevronDown','ChevronLeft','ChevronRight','ChevronsLeft','ChevronsRight','ArrowRight','ArrowUpRight','ArrowUp','ArrowDown','ArrowUpDown','Copy','Check','Download','FileSpreadsheet','BarChart3','Table2','Info','Lightbulb','X','Menu','Layers','TrendingUp','TrendingDown','Minus','Zap','CheckCircle2','ShieldCheck','Loader2','Rows3','Columns3','Filter','FolderOpen','PanelLeft','Inbox','MousePointerClick','Wand2','Flame','Eye','Lock','Table','Grid3x3','BarChartHorizontal','LineChart','PieChart','Activity','Clock']
const names = [...new Set([...a.questions.map(q => q.icon), ...a.categories.map(c => c.icon), ...d.kpis.map(k => k.icon), ...t.map(g => g.icon), ...ui])].sort()
const src = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit\nimport { ${names.join(', ')} } from 'lucide-react'\nconst MAP = { ${names.join(', ')} }\nexport default function Icon({ name, size = 18, ...p }) {\n  const C = MAP[name] || MAP.Sparkles\n  return <C size={size} strokeWidth={2} {...p} />\n}\n`
fs.writeFileSync('src/icons.jsx', src)
console.log(names.length + ' icons')
